%undefine _debugsource_packages
%define   _name           go-lib
%define   import_path     github.com/linuxdeepin/go-lib

Name:           golang-deepin-go-lib
Version:        6.0.6
Release:        1
Summary:        Go bindings for Deepin Desktop Environment development
License:        GPL-3.0-or-later
Group:          Development/Languages/Golang
URL:            https://github.com/linuxdeepin/go-lib
Source0:        https://github.com/linuxdeepin/go-lib/archive/%{version}/%{_name}-%{version}.tar.gz
# Generated by running, inside the source tree:
# export GOPATH=$(pwd)/.godeps
# go mod download
# tar cJf ../../godeps-for-go-libs-6.0.6.tar.xz .godeps
Source1:	godeps-for-go-libs-6.0.6.tar.xz

BuildRequires:  fdupes
# BuildRequires:  golang-github-linuxdeepin-go-x11-client
BuildRequires:  golang
BuildRequires:  mobile-broadband-provider-info
BuildRequires:  pam-devel
BuildRequires:  golang(github.com/linuxdeepin/go-gir/gio-2.0)
BuildRequires:  golang(github.com/linuxdeepin/go-gir/glib-2.0)
BuildRequires:  pkgconfig(alsa)
BuildRequires:  pkgconfig(gdk-pixbuf-2.0)
BuildRequires:  pkgconfig(gdk-pixbuf-xlib-2.0)
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(libcanberra)
BuildRequires:  pkgconfig(libpulse)
BuildRequires:  pkgconfig(x11)
BuildArch:      noarch
# Requires:       golang-github-linuxdeepin-go-x11-client
Requires:       golang(github.com/linuxdeepin/go-gir/gio-2.0)
Requires:       golang(github.com/linuxdeepin/go-gir/glib-2.0)

%description
DLib is a set of Go bindings/libraries for DDE development.
Containing dbus (forking from guelfey), glib, gdkpixbuf, pulse and more.

%prep
%autosetup -p1 -a1 -n %{_name}-%{version}

%build
export GOPATH=$(pwd)/.godeps:$(pwd)/gopath

go generate
cd generator
go build
cd ../test
go build

%install
export GOPATH=$(pwd)/.godeps:$(pwd)/gopath
make install DESTDIR=%{buildroot}

install -m 0644 %{_builddir}/go/src/%{import_path}/gdkpixbuf/blur.c \
                %{buildroot}%{go_contribsrcdir}/%{import_path}/gdkpixbuf/
install -m 0644 %{_builddir}/go/src/%{import_path}/gdkpixbuf/gaussianiir2d.c \
                %{buildroot}%{go_contribsrcdir}/%{import_path}/gdkpixbuf/
install -m 0644 %{_builddir}/go/src/%{import_path}/gdkpixbuf/gdk_pixbuf_utils.c \
                %{buildroot}%{go_contribsrcdir}/%{import_path}/gdkpixbuf/
install -m 0644 %{_builddir}/go/src/%{import_path}/pulse/dde-pulse.c \
                %{buildroot}%{go_contribsrcdir}/%{import_path}/pulse/
install -m 0644 %{_builddir}/go/src/%{import_path}/pulse/meter.c \
                %{buildroot}%{go_contribsrcdir}/%{import_path}/pulse/
install -m 0644 %{_builddir}/go/src/%{import_path}/sound/player.c \
                %{buildroot}%{go_contribsrcdir}/%{import_path}/sound/
# install -m 0644 %{_builddir}/go/src/%{import_path}/sound_effect/wav.c \
#                 %{buildroot}%{go_contribsrcdir}/%{import_path}/sound_effect/
install -m 0644 %{_builddir}/go/src/%{import_path}/stb_vorbis/stb_vorbis.c \
                %{buildroot}%{go_contribsrcdir}/%{import_path}/stb_vorbis/
install -m 0644 %{_builddir}/go/src/%{import_path}/pam/transaction.c \
                %{buildroot}%{go_contribsrcdir}/%{import_path}/pam/
# install -m 0644 %{_builddir}/go/src/%{import_path}/gm/sm2/dde-sm2.c \
#                 %{buildroot}%{go_contribsrcdir}/%{import_path}/gm/sm2/
#rm -rf %{buildroot}%{go_contribsrcdir}/%{import_path}/vendor
#gofilelist

%fdupes %{buildroot}

%files -f file.lst
%defattr(-,root,root)
%doc README.md
%license LICENSE
